version: '3.8'
services:
  db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres

      volumes:
        - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data: