# Generated by Django 4.1 on 2022-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "key",
                    models.CharField(max_length=255, unique=True, verbose_name="Key"),
                ),
                ("in_use", models.BooleanField(default=False, verbose_name="In use")),
                (
                    "is_exhausted",
                    models.BooleanField(default=False, verbose_name="Is exhausted"),
                ),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
    ]
